name: Build and Deploy
on: push
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            # Prepare Angular environment prod file
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - run: node setup-environment.js
              env:
                NG_ENVIRONMENT: '${{ secrets.NG_ENVIRONMENT }}'
            
            # Prepare Angular build
            - run: yarn
            
            # Build Angular app
            - run: yarn build:prod

            # Deploy app
            -   name: Deploy artifact
                uses: appleboy/scp-action@v0.1.7
                with:
                    host: ${{ secrets.TARGET_HOST }}
                    username: ${{ secrets.TARGET_USER }}
                    password: ${{ secrets.TARGET_PASSWORD }}
                    fingerprint: ${{ secrets.TARGET_FINGERPRINT }}
                    source: "dist/ngAbi/*"
                    rm: true
                    target: ngAbi
